------------------------------------------------------^
^------------------------------------------------------
version: 2

updates:

  # Enable version updates for GitHub ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
---------------------------------------------------|

version: 2

updates:

  # Enable version updates for GitHub ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
+|------------------------------------------------------^      
ยง  
@op.europa.eu
----------------------------------------------------^
^------------------------------------------------------
version: 2

updates:

  # Enable version updates for GitHub ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
---------------------------------------------------|

version: 2

updates:

  # Enable version updates for GitHub ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
+|------------------------------------------------------^      
ยง  
@op.europa.eu
