//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlassian.Bitbucket.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BitbucketResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BitbucketResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlassian.Bitbucket.UI.BitbucketResources", typeof(BitbucketResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string AuthorizeLabel {
            get {
                return ResourceManager.GetString("AuthorizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueLabel {
            get {
                return ResourceManager.GetString("ContinueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Bitbucket.
        /// </summary>
        public static string CredentialsWindowTitle {
            get {
                return ResourceManager.GetString("CredentialsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need an account?.
        /// </summary>
        public static string DoNotHaveAccountText {
            get {
                return ResourceManager.GetString("DoNotHaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t log in?.
        /// </summary>
        public static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about 2-Factor Authentication.
        /// </summary>
        public static string LearnMoreLink {
            get {
                return ResourceManager.GetString("LearnMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or username.
        /// </summary>
        public static string LoginPromptText {
            get {
                return ResourceManager.GetString("LoginPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username or email is required.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Authentication.
        /// </summary>
        public static string OAuthAuthText {
            get {
                return ResourceManager.GetString("OAuthAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth authentication required.
        /// </summary>
        public static string OAuthWindowTitle {
            get {
                return ResourceManager.GetString("OAuthWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPromptText {
            get {
                return ResourceManager.GetString("PasswordPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bitbucket.org/account/password/reset/.
        /// </summary>
        public static string PasswordResetUrl {
            get {
                return ResourceManager.GetString("PasswordResetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for an account.
        /// </summary>
        public static string SignUpLinkText {
            get {
                return ResourceManager.GetString("SignUpLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bitbucket.org/account/signup/.
        /// </summary>
        public static string SignUpLinkUrl {
            get {
                return ResourceManager.GetString("SignUpLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://confluence.atlassian.com/bitbucket/two-step-verification-777023203.html.
        /// </summary>
        public static string TwoFactorLearnMoreLinkUrl {
            get {
                return ResourceManager.GetString("TwoFactorLearnMoreLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string VerifyText {
            get {
                return ResourceManager.GetString("VerifyText", resourceCulture);
            }
        }
    }
}
