name: Experimental feature issues
description: A problem or issue occurred when using an experimental feature.
labels: ["experimental"]

body:
  - type: input
    id: version
    attributes:
      label: GCM Version
      description: |
        Which version of GCM are you using?

        From a terminal, run `git credential-manager --version` and paste the output.
      placeholder: >
        "Example: Git Credential Manager version 2.0.8-beta+e1f8492d04
        (macOS, .NET Core 4.6.27129.04)"
  - type: checkboxes
    id: provider
    attributes:
      label: Git Host Provider
      description: Which Git host provider are you trying to connect to?
      options:
        - label: Azure DevOps
        - label: Azure DevOps Server (TFS/on-prem)
        - label: GitHub
        - label: GitHub Enterprise
        - label: BitBucket
        - label: Other - please describe
  - type: checkboxes
    id: browserAccess
    attributes:
      label: Browser Access
      description: |
        Can you access the remote repository directly in the browser using the remote URL?

        From a terminal, run `git remote -v` to see your remote URL.
      options:
        - label: Yes
        - label: No, I get a permission error
        - label: No, for a different reason - please describe
  - type: checkboxes
    id: urlFormat
    attributes:
      label: _[Azure DevOps only]_ Remote URL format
      description: If you are using Azure DevOps, what format is your remote URL?
      options:
        - label: Not applicable
        - label: https://dev.azure.com/`{org}`/...
        - label: https://`{org}`@dev.azure.com/`{org}`/...
        - label: https://`{org}`.visualstudio.com/...
  - type: checkboxes
    id: identity
    attributes:
      label: _[Azure DevOps only]_ Account Identity
      description: >
        If you are using Azure DevOps and the account picker shows more than one
        identity as you authenticate, check that you selected the same one that
        has access on the web.
      options:
        - label: Not applicable
        - label: I only see one identity
        - label: I checked each identity and none worked
  - type: textarea
    id: expectedBehavior
    attributes:
      label: Expected Behavior
      placeholder: I am authenticated and my git operation completes successfully.
  - type: textarea
    id: actualBehavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what happens.
      placeholder: Exception is thrown, UI freezes, etc.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your
        Git command. Review and redact any private information and attach the log.

        If you are running inside of Windows Subsystem for Linux (WSL), you must also
        set an additional environment variable to enable tracing: `WSLENV=$WSLENV:GCM_TRACE`.
        For example:

        ```shell
        WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
        ```
