name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none

resources:
  repositories:
    - repository: 1ESPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

variables:
  - name: 'esrpAppConnectionName'
    value: '1ESGitClient-ESRP-App'
  - name: 'esrpMIConnectionName'
    value: '1ESGitClient-ESRP-MI'
  # ESRP signing variables set in the pipeline settings:
  # - esrpEndpointUrl
  # - esrpClientId
  # - esrpTenantId
  # - esrpKeyVaultName
  # - esrpSignReqCertName

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelines
  parameters:
    sdl:
      # SDL source analysis tasks only run on Windows images
      sourceAnalysisPool:
        name: GitClientPME-1ESHostedPool-intel-pc
        image: win-x86_64-ado1es
        os: windows
    stages:
      - stage: adhoc
        displayName: 'Adhoc Sign'
        jobs:
          - job: adhoc_sign
            displayName: 'Sign'
            pool:
              name: GitClientPME-1ESHostedPool-intel-pc
              image: win-x86_64-ado1es
              os: windows
              hostArchitecture: amd64
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: '$(Build.ArtifactStagingDirectory)\_final'
                  artifactName: 'outputs'
            steps:
              - checkout: none
              - task: PowerShell@2
                displayName: 'Download unsigned packages'
                inputs:
                  pwsh: true
                  targetType: inline
                  script: |
                    New-Item -Path "$(Build.ArtifactStagingDirectory)/tosign" -ItemType Directory -Force
                    Invoke-WebRequest -Uri "https://github.com/git-ecosystem/git-credential-manager/releases/download/v3.0.1/git-credential-manager.3.0.1.nupkg" -OutFile "$(Build.ArtifactStagingDirectory)/tosign/git-credential-manager.3.0.1.nupkg"
                    Invoke-WebRequest -Uri "https://github.com/git-ecosystem/git-credential-manager/releases/download/v3.0.0/git-credential-manager.3.0.0.nupkg" -OutFile "$(Build.ArtifactStagingDirectory)/tosign/git-credential-manager.3.0.0.nupkg"
              - template: .azure-pipelines/esrp/sign.yml@self
                parameters:
                  displayName: 'Sign packages'
                  folderPath: '$(Build.ArtifactStagingDirectory)/tosign'
                  pattern: '**/*.nupkg'
                  inlineOperation: |
                    [
                      {
                        "KeyCode": "CP-401405",
                        "OperationCode": "NuGetSign",
                        "ToolName": "sign",
                        "ToolVersion": "1.0",
                        "Parameters": {}
                      }
                    ]
              - task: PowerShell@2
                displayName: 'Collect artifacts'
                inputs:
                  targetType: inline
                  script: |
                    New-Item -Path "$(Build.ArtifactStagingDirectory)\_final" -ItemType Directory -Force
                    Copy-Item -Path "$(Build.ArtifactStagingDirectory)\tosign\*.nupkg" -Destination "$(Build.ArtifactStagingDirectory)\_final"
